### ISSUE TITLE
[FEAT] resolve import errors with ovos-utils 0.1.0

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/neon-utils#514]
### Objective

For full support with ovos-utils 0.1.0+, some import errors need to be resolved (see below)

### Initial Implementation Requirements

```
2024-04-27 22:11:13.593 - neon-utils - neon_utils.configuration_utils:_init_ovos_conf:512 - ERROR - Failed to override mycroft.configuration: cannot import name 'play_acknowledge_sound' from 'ovos_utils.sound' (/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/ovos_utils/sound.py)
2024-04-27 22:11:13.598 - neon-utils - neon_core.util.skill_utils:update_default_resources:137 - INFO - Directory exists; not linking default resources. /Users/Mike/.cache/neon/res
Traceback (most recent call last):
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/bin/neon", line 8, in <module>
    sys.exit(neon_core_cli())
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_core/cli.py", line 104, in run_skills
    from neon_core.skills.__main__ import main
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_core/skills/__init__.py", line 29, in <module>
    from neon_core.skills.decorators import intent_handler, intent_file_handler, \
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/neon_core/skills/decorators.py", line 37, in <module>
    from mycroft.skills.mycroft_skill.decorators import intent_handler, \
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/mycroft/__init__.py", line 18, in <module>
    from mycroft.messagebus.message import Message
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/mycroft/messagebus/__init__.py", line 14, in <module>
    from mycroft.messagebus.client.client import MessageBusClient
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/mycroft/messagebus/client/__init__.py", line 15, in <module>
    from mycroft.messagebus.client.client import MessageBusClient
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/mycroft/messagebus/client/client.py", line 20, in <module>
    import mycroft.util.process_utils
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/mycroft/util/__init__.py", line 22, in <module>
    from mycroft.util.audio_utils import (play_audio_file, play_wav, play_ogg,
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/mycroft/util/audio_utils.py", line 20, in <module>
    from ovos_utils.sound import play_acknowledge_sound, play_listening_sound, \
ImportError: cannot import name 'play_acknowledge_sound' from 'ovos_utils.sound' (/Users/Mike/Library/Caches/pypoetry/virtualenvs/neon-mac-sv8wqWXe-py3.10/lib/python3.10/site-packages/ovos_utils/sound.py)
```

**Comment by mikejgray** [comment]
I think I was just using an outdated version of the code...will close for now
